---
title: "Week 4 - Predicting Change"
author: "Team 1"
date: '2022-04-12'
output: html_document
---

```{r programs to load, results='asis'}
# load necessary packages ----
library( dplyr )
library( here )
library( knitr )
library( pander )
library( stargazer )
library( scales )

# set randomization seed ----
set.seed( 1234 )

# load necessary functions and objects ----
# note: all of these are R objects that will be used throughout this .rmd file
import::here("S_TYPE",
             "panel.cor",
             "panel.smooth",
             "jplot",
             "d",
             "df",
             "cbsa_stats_df",
             # notice the use of here::here() that points to the .R file
             # where all these R objects are created
             .from = here::here("labs/wk04/lab_04_source.R"),
             .character_only = TRUE) 
S_TYPE <-"text"
INFLATION_RATE <- 1.28855 
```

```{r Data, results='asis'}
# load necessary data ----
# remember to use the here::here() function
d1 <- readRDS( here::here( "data/rodeo/LTDB-2000.rds" ) )
d2 <- readRDS( here::here( "data/rodeo/LTDB-2010.rds" ) )
md <- readRDS( here::here( "data/rodeo/LTDB-META-DATA.rds" ) )

d1 <- dplyr::select( d1, - year )
d2 <- dplyr::select( d2, - year )

d <- merge( d1, d2, by="tractid" )
d <- merge( d, md, by="tractid" )

```


```{r Descriptives, results='asis'}
stargazer( df, 
           type="S.TYPE", 
           digits=0, 
           summary.stat = c("min", "p25","median","mean","p75","max") )
```

```{r Part 1 to find Variables, results='asis'}
#Just home value
df %>% head
#All variables
d %>% head()
```


Part 1 - Data
Similar to your previous lab, create a dataset that includes 2000 and 2010 census variables drop all rural census tracts.

Create a variable that measures the growth of median home value from 2000 to 2010.

Omit cases that have a median home value less than $10,000 in 2000.

Omit cases with growth rates above 200%.




```{r Part 1 ,results='asis }
MHV.Change.00.to.10 <- df$MHV.Change.00.to.10
MHV2000 <- df$MedianHomeValue2000


#Only Urban, no rurl
d <- filter( d, urban == "urban" )

d <- select( d, tractid, 
             mhmval00, mhmval12, 
             hinc00, 
             hu00, vac00, own00, rent00, h30old00,
             empclf00, clf00, unemp00, prof00,  
             dpov00, npov00,
             ag25up00, hs00, col00, 
             pop00.x, nhwht00, nhblk00, hisp00, asian00,
             cbsa, cbsaname,
             #NEW VARIABLE IDEAS
             #mar00,flabf00
             )
d <- 
  d %>%
  mutate( # percent white in 2000
          p.white = 100 * nhwht00 / pop00.x,
          # percent black in 2000
          p.black = 100 * nhblk00 / pop00.x,
          # percent hispanic in 2000
          p.hisp = 100 * hisp00 / pop00.x, 
          # percent asian in 2000
          p.asian = 100 * asian00 / pop00.x,
          # percent high school grads by age 25 in 2000 
          p.hs = 100 * (hs00+col00) / ag25up00,
          # percent pop with college degree in 2000
          p.col = 100 * col00 / ag25up00,
          # percent employed in professional fields in 2000
          p.prof = 100 * prof00 / empclf00,
          # percent unemployment  in 2000
          p.unemp = 100 * unemp00 / clf00,
          # percent of housing lots in tract that are vacant in 2000
          p.vacant = 100 * vac00 / hu00,
          # dollar change in median home value 2000 to 2010 
          pov.rate = 100 * npov00 / dpov00,
          # NEW VARIABLE percent married in 2000
          # p.mar = 100 * mar00 / pop00.x,
          # NEW VARIABLE percent females in the labor force
          #p.flabf00 =  100 * flabf00/empclf00 
          )

# adjust 2000 home values for inflation 
mhv.00 <- d$mhmval00 * INFLATION_RATE 
mhv.10 <- d$mhmval12

# change in MHV in dollars
mhv.change <- mhv.10 - mhv.00

# drop low 2000 median home values, to avoid unrealistic growth rates, tracts with homes that cost less than, $10,000 are outliers
#Omit cases that have a median home value less than $10,000 in 2000.
mhv.00[ mhv.00 < 10000 ] <- NA

# change in MHV in percent, 
mhv.growth <- 100 * ( mhv.change / mhv.00 )
d$mhv.00 <- mhv.00
d$mhv.10 <- mhv.10
d$mhv.change <- mhv.change
d$mhv.growth <- mhv.growth 

# Create a variable that measures the growth of median home value from 2000 to 2010.
MHV.Growth.00.to.10 <- ( MHV.Change.00.to.10 / MHV2000 )
mhv.growth <- ( mhv.change / mhv.00 )

# Omit cases with growth rates above 200%. 
# change in MHV.00.to.10 in percent, 
p.MHV.Growth.00.to.10 <- 100 * ( MHV.Change.00.to.10 / MHV2000 )

# Omit cases with growth rates above 200%.
p.MHV.Growth.00.to.10[ p.MHV.Growth.00.to.10 > 200 ] <- NA
mhv.growth[ mhv.growth > 200 ] <- NA

```

```{r Median Home Value, results='asis'}
hist( df$MedianHomeValue2000, breaks=200, xlim=c(0,500000), 
      col="gray20", border="white",
      axes=F, 
      xlab="MHV (median = $138k)",
      ylab="",
      main="Median Home Value in 2000 (2010 US dollars)" )

axis( side=1, at=seq(0,500000,100000), 
      labels=c("$0","$100k","$200k","$300k","$400k","$500k") )

abline( v=median( df$MedianHomeValue2000, na.rm=T ), col="orange", lwd=3 )
```

```{r Percent Change in MHV 2000 to 2010, results='asis }
hg <-
hist( df$MHV.Growth.00.to.12, breaks=5000, 
      xlim=c(-100,200), yaxt="n", xaxt="n",
      xlab="", cex.main=1.5,
      ylab="", main="Growth in Home Value by Census Tract 2000 to 2010",
      col="gray40", border="white" )

axis( side=1, at=seq( from=-100, to=200, by=50 ), 
      labels=paste0( seq( from=-100, to=200, by=50 ), "%" ) )

ymax <- max( hg$count )
        
mean.x <- mean( df$MHV.Growth.00.to.12, na.rm=T )
abline( v=mean.x, col="darkorange", lwd=2, lty=2 )
text( x=100, y=(0.5*ymax), 
      labels=paste0( "Mean = ", round(mean.x,0), "%"), 
      col="darkorange", cex=1.8, pos=4 )

median.x <- median( df$MHV.Growth.00.to.12, na.rm=T )
abline( v=median.x, col="dodgerblue", lwd=2, lty=2 )
text( x=100, y=(0.6*ymax), 
      labels=paste0( "Median = ", round(median.x,0), "%"), 
      col="dodgerblue", cex=1.8, pos=4 )
```